### ISSUE TITLE
Upload file list for tag

### ISSUE THREAD

**Issue by ameyer-cern** [cms-PdmV/GrASP#114]
I have a list of datasets that I would like to tag by topV_DESY here:
https://docs.google.com/document/d/1nymeVCZgsuexHpSzBdOLTBD-ljdg1Zv3jCKB_IdOKvY/edit
The easiest would be if I was able to upload a text file with this list for tagging.

Putting the whole string into the URL takes a looong time, but works, too.

With the current grasp, I went line by line, created the URL and then tagged everything. I found that there are a couple of datasets that are for testing, including "pilot" datasets (see previous issue) and "PUForMUOVal". Not sure what these are.
There are also JMENano, can we mark them somehow ?

I found the special cases by looking at the list of tagged datasets, https://cms-pdmv.cern.ch/grasp/tags?name=topV_DESY 
For some generators there are more than one set of mini and/or nano per campaign.

**Comment by justinasr** [comment]
- File upload added
- Pilot requests are ignored
- Added processing strings to GrASP, so JMENano requests have e.g. "20UL18JMENano"
