### ISSUE TITLE
Role "anonymous"

### ISSUE THREAD

**Issue by jennetd** [cms-PdmV/GrASP#120]
Hello, when I try to add a tag to samples in GrASP I get a pop-up that says:

API not allowed. User jdickins has role "anonymous", required "USER"

How can I get role "USER" ? Thanks.

**Comment by hessikaveh** [comment]
Hi Jennet, 
You need an McM user role. Please register by McM. More info can be found https://cms-pdmv.gitbook.io/project/reqmgr#how-to-increase-the-role-of-a-user 
https://twiki.cern.ch/twiki/bin/viewauth/CMS/McM

**Comment by jennetd** [comment]
Success! Thanks very much.
