### ISSUE TITLE
PMP link for collection of requests

### ISSUE THREAD

**Issue by ameyer-cern** [cms-PdmV/GrASP#79]
Hi all,

I would propose to implement a link (like in MCM)  that combines several requests to be displayed in PMP.

Concrete example: I would like to see the production history for these requests:
https://cms-pdmv.cern.ch/grasp/tags?name=HinvVBF&miniaod_version=MiniAODv1

Andreas

**Comment by justinasr** [comment]
Hello,

I suppose not all requests, but MiniAOD or NanoAOD only? All requests would lead to (at least) triple-counting events - GEN+Mini+Nano for each sample. I imagine buttons on top or below MiniAOD and NanoAOD columns that would point to pMp with all the visible MiniAOD or NanoAOD requests respectively?

**Comment by ameyer-cern** [comment]
Hi Justinas, 
Yeah, mini alone would already be cool. Or mini or nano. Should avoid double counting indeed 
A good weekend! 
Andreas

**Comment by justinasr** [comment]
When samples are selected using checkboxes on the right, a button "pMp Historical" appears at the bottom bar. This button will lead to pMp with last request of each sample - Nano if Nano exists OR Mini if Mini exists OR root request.
