### ISSUE TITLE
Select existing by data set name

### ISSUE THREAD

**Issue by jrueb** [cms-PdmV/GrASP#81]
**Is your feature request related to a problem? Please describe:**
I'm a normal user without any further permissions but I want to check the progress of the data sets my analysis depends on. Grasp is a very nice (if not the best) tool to see progresses, but it only displays them by campaign and group. This means that most of the data sets displayed do not interest me and it takes some searching until I find the ones I actually want to see.

**Describe the solution you'd like:**
Allow another parameter to the `existing` page that allows specifying data set names. This would work the same way as the `name` parameter, allowing wildcards and commas. This would simplify searching and also allows using a single URL one can regularly check or send to other people.

For me, this would largely improve the usage of Grasp.

**Comment by justinasr** [comment]
Hi,
You can already have a filter on the dataset name, for example:
https://cms-pdmv.cern.ch/grasp/existing?name=RunIISummer19UL16*GEN&dataset=electron 
This is the same as typing "electron" to the search manually:
![Screenshot from 2021-06-23 14-52-47](https://user-images.githubusercontent.com/9316557/123099844-d8760a80-d432-11eb-90bd-108b290e9b13.png)
These search fields are based on regex, so "OR" would look like this: "(electron|muon)" meaning electron OR muon.

However, in the link above, results are limited to Summer19UL16 campaign. You can specify multiple campaigns with a comma:
https://cms-pdmv.cern.ch/grasp/existing?name=RunIISummer19UL16*GEN,RunIISummer19UL16*GENAPV,RunIISummer19UL17*GEN,RunIISummer19UL18*GEN&dataset=electron
Just be aware that specifying multiple campaigns in the URL, will actually fetch all of them, so rendering a table of 4 campaigns will be slow.

**Comment by jrueb** [comment]
Thanks! I wasn't fully aware of this filter. However it doesn't seem to allow selecting multiple data set names. I would like to see only selected few data sets, which have rather different names, for example `TTToHadronic_TuneCP5CR2_13TeV-powheg-pythia8` and `ST_t-channel_top_4f_InclusiveDecays_TuneCP5_erdON_13TeV-powheg-madspin-pythia8`. It would be nice if the comma syntax was allowed here as well (and maybe also the asterisk.

**Comment by justinasr** [comment]
Hi,
At the moment, you can use `|` as the "OR" operator, i.e.:
https://cms-pdmv.cern.ch/grasp/existing?name=RunIISummer19UL16*GEN&dataset=TTToHadronic_TuneCP5CR2_13TeV-powheg-pythia8|ST_t-channel_top_4f_InclusiveDecays_TuneCP5_erdON_13TeV-powheg-madspin-pythia8
Maybe we could add "comma support" by just replacing commas with `|`. 

Asterisks are supported already, e.g.:
https://cms-pdmv.cern.ch/grasp/existing?name=RunIISummer19UL16*GEN&dataset=TTToHadronic_|ST_t-channel_*down

**Comment by jrueb** [comment]
Oh, thanks, that's super useful!
Then everything I wanted is already implemented.
