### ISSUE TITLE
Link GrASP from twiki and gitbook

### ISSUE THREAD

**Issue by DryRun** [cms-PdmV/GrASP#82]
Not exactly a feature request, but it would be nice if GrASP were easier to find for users that don't remember the URL. A link on https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmV and https://cms-pdmv.gitbook.io/project/group-analysis-samples-page-grasp would be great, and anywhere else it might be appropriate. 

It's also hard to find on Google ("cms grasp" has no hits, "cms pdmv grasp" has one hit with the URL from gitmemory.com), but maybe this is by design. Also, twiki search, but that might be hopeless.

**Comment by justinasr** [comment]
Hello,
Point taken, added link to TWiki and to gitbook. We also have a [PdmV Homepage](https://cms-pdmv.cern.ch/home/) that has a link to GrASP. I also added a link to GrASP repo (this) which should come up as a result in Google.

Not sure about Google search itself though, our websites are behind CERN SSO, so they can't be indexed. Probably GrASP iself will never appear as a result there.
TWiki and it's search is beyond my expertise, does not seem to find links to any of the tools.

**Comment by DryRun** [comment]
Thanks a lot, @justinasr !
