### ISSUE TITLE
Removal of outdated UL19 campaigns and addition of Run3 campaigns 

### ISSUE THREAD

**Issue by hessikaveh** [cms-PdmV/GrASP#86]
**Is your feature request related to a problem? Please describe:**
The UL19 samples are out Dated due to bugs in their productions.
The Run3 campaigns are not included but monitoring is requested from groups.

**Describe the solution you'd like:**
Removing UL19 and addition of Run3 tags.

**Comment by justinasr** [comment]
Not a bug or a feature of GrASP
