### ISSUE TITLE
Download table does not work

### ISSUE THREAD

**Issue by jrueb** [cms-PdmV/GrASP#94]
**Describe the bug:**
Trying to download the table from a GrASP page via the "CSV" or "XLS" links does not work, it does nothing.

**To reproduce:**
1. Go to https://cms-pdmv.cern.ch/grasp/existing?name=RunIISummer20UL16*GEN&pwg=B2G (or any other GrASP page)
2. Click on "CSV" on the top right
3. Nothing happens

**Expected behavior:**
Getting prompted to start the download of a CSV file

**Browser (optional, please fill in only if you are experiencing visual bugs):**
Firefox 94

**Additional context (optional):**
I see a JavaScript error message in my browser console popping up saying `TypeError: this.campaign.name is undefined`

**Comment by hessikaveh** [comment]
Hi, Thanks for reporting the problem (it's due to a variable name not updated to the latest in the previous update to the code), will be fixed soon in the new open pull request!
