### ISSUE TITLE
No such column: tags

### ISSUE THREAD

**Issue by DryRun** [cms-PdmV/GrASP#95]
**Describe the bug:**
Attempting to load a GrASP table gives a popup error:
"cms-pdvm.cern.ch  says
no such column: tags"

This happens even if "tags" is not in the URL query string.

Also, the tables seem not to be loading (still loading after 10 minutes for a small query; might be a separate issue). 

**To reproduce:**
1. I think this happens for any query. I encountered it at https://cms-pdmv.cern.ch/grasp/existing?name=RunIISummer20UL16*GEN,RunIISummer20UL16*GENAPV,RunIISummer20UL17*GEN,RunIISummer20UL18*GEN&dataset=QCD_HT*

**Expected behavior:**
Tags should work. 

**Screenshots (optional):**

**Browser (optional, please fill in only if you are experiencing visual bugs):**
Browser name [e.g. chrome, firefox, safari]

**Additional context (optional):**

**Comment by hessikaveh** [comment]
Due to the latest update, we need to re-populate the databases! and this error is caused by the tags not being in the database tables! It will be resolved as soon as we can update them again, sorry for the inconvenience!

**Comment by DryRun** [comment]
Looks good now, thanks!

**Comment by DryRun** [comment]
Sorry, I spoke too soon. The error went away, but the table for a given tag isn't loading. For example, https://cms-pdmv.cern.ch/grasp/tags?name=DAZSLE.

**Comment by hessikaveh** [comment]
It will take a few hours! We just put a quick fix, but the tables have to update for it to work as expected!

**Comment by hessikaveh** [comment]
Hi @DryRun, do you confirm that the issue is resolved now?
